[[CURRENCIES]]
code="ALFP"
issuer="GDJUO6AKCNIH3HVQPNQHKFCTZGESQPM4XWUN7YRCWPLTB6GSUXIWD23J"
name="ALFPay Token"
desc="ALFPay Token test utility token on Pi Testnet."
image="https://alfoncekomba38-eng.github.io/alfp-pi-token/alfp.png"
