[[CURRENCIES]]
code="ALFP"
issuer="GBTQOBWJSXR4CFKRRH5DTU3BP5AD7ECJSNOQVXQYWET5MQGQBCRALZUU"
name="ALFPay Token"
desc="ALFPay Token test utility token on Pi Testnet."
image="https://alfoncekomba38-eng.github.io/alfp-pi-token/alfp.png"
